/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package org.etcd;

import java.util.List;

import org.dynamicconfig.Config;
import org.dynamicconfig.DynamicConfig;

public class App {
    public String getGreeting() {
        return "Hello World!";
    }

    public static void main(String[] args) {
        DynamicConfig dynamicConfig = DynamicConfig.builder().endpoints("http://localhost:2479")
                .setAuth("CRYPTO", "CRYPTO1234").build();

        try {
            List<Config> configs = dynamicConfig.getMultipleConfig(3);
            System.out.println(configs.toString());
        } catch (Exception e) {
            System.out.println(e);
        }

        // need to close the client in order to kill the thread
        dynamicConfig.getClient().close();

    }
}
