/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package org.etcd;

import java.util.concurrent.CompletableFuture;

import io.etcd.jetcd.ByteSequence;
import io.etcd.jetcd.Client;
import io.etcd.jetcd.KV;
import io.etcd.jetcd.kv.GetResponse;
import io.etcd.jetcd.options.GetOption;

public class App {
    public String getGreeting() {
        return "Hello World!";
    }

    public static void main(String[] args) {
        ByteSequence username = ByteSequence.from("CRYPTO".getBytes());
        ByteSequence password = ByteSequence.from("CRYPTO1234".getBytes());
        Client client = Client.builder().endpoints("http://localhost:2479").password(password).user(username).build();

        KV kvClient = client.getKVClient();

        ByteSequence key = ByteSequence.from("config/CRYPTO".getBytes());
        kvClient.get(key);

        GetOption getOption = GetOption.newBuilder().isPrefix(true).build();
        CompletableFuture<GetResponse> getFuture = kvClient.get(key, getOption);
        try {
            GetResponse response = getFuture.get();
            System.out.println(response.getCount());
        } catch (Exception e) {
            System.out.println(e);
        }

    }
}
