/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package org.etcd;

import org.dynamicconfig.DynamicConfig;

public class App {
    public String getGreeting() {
        return "Hello World!";
    }

    public static void main(String[] args) {
        DynamicConfig dynamicConfig = DynamicConfig.builder().endpoints("http://localhost:2479")
                .setAuth("CRYPTO", "CRYPTO1234").build();

        for (int i = 0; i < 10; i++) {
            try {
                String sellValue = dynamicConfig.getSingleConfig("SELL_VALUE");
                System.out.printf("%d, %s \n", i, sellValue);
            } catch (Exception e) {
                System.out.println(e);
            }
        }

        // need to close the client in order to kill the thread
        dynamicConfig.getClient().close();

    }
}
